[package]
name = "rust_playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# database
rusqlite = { version = "0.31.0", features = ["bundled"] }
lazy_static = "1.4.0"
